{% set name = "mdacli" %}
{% set version = "0.1.34" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdacli-{{ version }}.tar.gz
  sha256: 325552acb9e77d9ab665854bb111ddd0ae629f156621f201cef11131b0a689f6

build:
  entry_points:
    - mda = mdacli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mdanalysis >=2.10.0
    - threadpoolctl
    - argcomplete

test:
  imports:
    - mdacli
  commands:
    - pip check
    - mda --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/MDAnalysis/mdacli
  summary: A command line client for MDAnalysis Analysis classes.
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    mdacli is a simple command line interface (CLI) to the analysis
    classes of MDAnalysis using argparse.
  doc_url: https://mdacli.mdanalysis.org
  dev_url: https://github.com/MDAnalysis/mdacli

extra:
  recipe-maintainers:
    - hejamu
    - PicoCentauri
