{% set name = "mdacli" %}
{% set version = "0.1.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdacli-{{ version }}.tar.gz
  sha256: f4c4fc8664d6a4abbb90751bfc500adaec6d0c29b0f83e174c379b457d426f37

build:
  entry_points:
    - mda = mdacli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mdanalysis >=2.1.0
    - threadpoolctl

test:
  imports:
    - mdacli
  commands:
    - pip check
    - mda --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/MDAnalysis/mdacli
  summary: A command line client for MDAnalysis Analysis classes.
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    mdacli is a simple command line interface (CLI) to the analysis
    classes of MDAnalysis using argparse.
  doc_url: https://mdacli.mdanalysis.org
  dev_url: https://github.com/MDAnalysis/mdacli

extra:
  recipe-maintainers:
    - PicoCentauri
