{% set name = "mdacli" %}
{% set version = "0.1.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d47a0421d6ab46f4b6f26788b923e45b9ed805c5bffce13c3536a033f804ee50

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - MDAnalysis >=2.1.0
    - threadpoolctl

test:
  imports:
    - mdacli

about:
  home: https://github.com/MDAnalysis/mdacli
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Command line interface for MDAnalysis
  description: |
    mdacli is a simple command line interface (CLI) to the analysis
    classes of MDAnalysis using argparse.
  doc_url: https://mdacli.mdanalysis.org
  dev_url: https://github.com/MDAnalysis/mdacli

extra:
  recipe-maintainers:
    - PicoCentauri
