{% set name = "mdacli" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ad55858a94d1b8c77acacb8ec13b5dfd41dc03d545dfe775601b429be69e016

build:
  number: 0
  skip: true  # [py<39]
  skip: true  # [py>39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - MDAnalysis >=2.0.0

test:
  imports:
    - mdacli

about:
  home: https://github.com/MDAnalysis/mdacli
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Command line interface for MDAnalysis
  description: |
    mdacli is a simple command line interface (CLI) to the analysis
    classes of MDAnalysis using argparse.
  doc_url: https://mdacli.mdanalysis.org
  dev_url: https://github.com/MDAnalysis/mdacli

extra:
  recipe-maintainers:
    - PicoCentauri
